name: A workflow for my Fibonacci action
on: pull_request

jobs:
  build:
    name: Run the Fibonacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./cpa
        with:
          N_INDEX: 12
